source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 7.0', '>= 7.0.4.2'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

# Use webpack to manage app-like JavaScript modules in Rails
gem 'webpacker', '~> 5.4', '>= 5.4.3'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'pry-rails'
	gem 'pry-remote'
	gem 'pry-byebug'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

#importando materialize
# gem 'jquery-rails'
# gem 'materialize-sass'
# gem 'material_icons'
# gem 'sass-rails'

#adicionando sqlite
gem 'sqlite3', '~> 1.3', '>= 1.3.11'

gem 'ati_style', git: 'https://c0d2a89b2df6f3f9e0030251776e599dbd2ed7fe@gitea.ati.to.gov.br/joao.miguel/ati_style.git'

gem 'json'
gem 'oj'
gem 'httparty'
gem 'listen'
gem 'i18n'
gem 'ransack'
# gem "recaptcha"